version: '3.8'

services:
  app:
    build:  
      context: . 
      dockerfile: Dockerfile 
    image: web-python-flask 
    ports: 
      - "5000:5000" 
    environment: 
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/sistema_matricula 
    networks: 
      - mireddistribuida 

  db: 
    image: postgres:latest 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin123 
      POSTGRES_DB: sistema_matricula 
    ports: 
      - "5432:5432" 
    networks: 
      - mireddistribuida 

networks: 
  mireddistribuida: 
    driver: bridge
